# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dd8a5b8d401d338bb12e8560579c2482eb258bb92734f2051daca4909f0153f7156ac2e4a8d4f984fbcf6c578c1579ee9a08d45de4bba354b5d1ff958d91583

test:
  secret_key_base: d60a9918bfc1b95b6d7ff3a1a86c01e930e18907d79e1ddbf22aa6c29eb9c3a574c8d82ea2a21391c1c918b51d0edc8200f979e162793cfe57831340fd6c6189

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
